site_name: ProSAP
site_url: https://example.com/
nav:
    - Home: index.md
    - Installation: setup.md
    - Getting started: features.md
    - Document: 
        Preprocess: preprocess.md
        PISA and iTSA analysis: PISA_ITSA.md
        TPP and NPA analysis: TPP_NPA.md
        TPCA analysis: TPCA.md
        TPP-2D analysis: 2D_TPP.md
    - About: about.md
    
extra_javascript:
    - 'js/baidu-tongji.js'    
